spring:
  application:
    name: Stock Service
    
server:
  port: 8046
 

    
eureka:
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://localhost:8047/eureka/
  instance:
     hostname: localhost      

    
      


     
       
       
       
       

   
   
